# Generated by Django 5.2.9 on 2026-01-09 07:24

import django.db.models.manager
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0005_post_archived_alter_comment_post'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='post',
            managers=[
                ('not_archived', django.db.models.manager.Manager()),
            ],
        ),
    ]
