# Generated by Django 5.2.7 on 2025-10-14 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0006_auto_20240215_1044'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='tags',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='engagement_count',
            field=models.PositiveIntegerField(default=0),
            preserve_default=False,
        ),
    ]
