# Generated by Django 5.2.10 on 2026-02-03 11:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0003_product'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, unique=True)),
                ('created_date', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('modified_date', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='order',
            name='created_date',
        ),
        migrations.RemoveField(
            model_name='order',
            name='modified_date',
        ),
        migrations.RemoveField(
            model_name='order',
            name='title',
        ),
        migrations.AddField(
            model_name='product',
            name='order',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.PROTECT, to='order.order'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='order',
            name='info',
            field=models.OneToOneField(default='', on_delete=django.db.models.deletion.PROTECT, to='order.orderinfo'),
            preserve_default=False,
        ),
    ]
