# Generated by Django 5.2.10 on 2026-02-03 11:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0005_remove_product_order_order_product_productitem'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='orderinfo',
            options={'ordering': ['-created_date'], 'verbose_name': 'info of order'},
        ),
        migrations.AlterUniqueTogether(
            name='orderinfo',
            unique_together={('title', 'created_date')},
        ),
        migrations.AlterModelTable(
            name='orderinfo',
            table='order_info',
        ),
    ]
