# Generated by Django 5.2.11 on 2026-02-17 19:39

import django.db.models.manager
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0004_posttemplate_post_archived_post_engagement_count_and_more'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='post',
            managers=[
                ('not_archived', django.db.models.manager.Manager()),
            ],
        ),
    ]
